"""empty message

Revision ID: 049abe757493
Revises: fb5d4f87b309
Create Date: 2021-11-30 14:36:32.113562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049abe757493'
down_revision = 'fb5d4f87b309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('NEWS', 'PUBLICATION', 'OTHER', name='posttype'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
