"""empty message

Revision ID: 2045fc203129
Revises: 194a8517aea7
Create Date: 2021-11-19 15:27:26.127615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2045fc203129'
down_revision = '194a8517aea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
