"""empty message

Revision ID: 413616caff84
Revises: 27c07a349c2c
Create Date: 2021-11-05 11:30:46.681668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413616caff84'
down_revision = '27c07a349c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['first_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
