"""empty message

Revision ID: 0354567be890
Revises: 1ac0097a2ac8
Create Date: 2021-12-04 08:50:09.897872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0354567be890'
down_revision = '1ac0097a2ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
