"""empty message

Revision ID: 194a8517aea7
Revises: 413616caff84
Create Date: 2021-11-05 11:40:07.889029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194a8517aea7'
down_revision = '413616caff84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
