"""empty message

Revision ID: 1ac0097a2ac8
Revises: eea434be01a3
Create Date: 2021-12-03 17:30:51.134075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac0097a2ac8'
down_revision = 'eea434be01a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoryacr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_inst', sa.String(length=50), nullable=False),
    sa.Column('count_student', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('military_department', sa.Boolean(), nullable=False),
    sa.Column('category_acr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_acr_id'], ['categoryacr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution')
    op.drop_table('categoryacr')
    # ### end Alembic commands ###
