"""empty message

Revision ID: 82757bfd7f35
Revises: fe2184853110
Create Date: 2021-11-05 10:55:26.541171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82757bfd7f35'
down_revision = 'fe2184853110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
