"""empty message

Revision ID: fe2184853110
Revises: 
Create Date: 2021-11-05 10:45:44.259353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2184853110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username2', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['username2'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username2')
    # ### end Alembic commands ###
